#!/usr/bin/env python3
"""make_staged_manifest.py: write staged_manifest.tsv, the expected content of the staged
learner copy ($STAGED in config.sh), with size and md5 for every file.

Run on the laptop, where verified copies of every staged file exist:
    python3 negishi-run/make_staged_manifest.py
Sources: FASTQ, mart.tsv, annot.tsv from the January staging copy in local-test/; the four
GENCODE vM38 references from the 2026-10-01 episode 02 download (md5-identical to the staged
copies in the 2026-10-02 Negishi kit run); SRR_Acc_List.txt and tx2gene.tsv
regenerated into negishi-run/staged-data/ (not stored in git); scripts from negishi-run/staged-scripts/ (generated by build_kit.py).
check_staged.sh and 00_preflight.sh read the manifest.
"""
import hashlib
import pathlib

KIT = pathlib.Path(__file__).resolve().parent
LT = KIT.parent / "local-test"
SAMPLES = ["WT_Bcell_%s_rep%d" % (c, i) for c in ("IR", "mock") for i in range(1, 5)]

SOURCES = []
for s in SAMPLES:
    for r in ("R1", "R2"):
        SOURCES.append(("data/%s_%s.fastq.gz" % (s, r), LT / ("rnaseq-workshop/data/%s_%s.fastq.gz" % (s, r)),
                        "January 2026 staging (seqtk sample -s 42, 20 M pairs)"))
for f in ("mart.tsv", "annot.tsv"):
    SOURCES.append(("data/" + f, LT / "rnaseq-workshop/data" / f, "January 2026 staging (biomaRt)"))
for f in ("GRCm39.primary_assembly.genome.fa", "gencode.vM38.primary_assembly.basic.annotation.gtf",
          "gencode.vM38.transcripts.fa", "gencode.vM38.transcripts-clean.fa"):
    SOURCES.append(("data/" + f, LT / "scratch/rnaseq-workshop/data" / f, "GENCODE vM38 via episode 02 (uncompressed)"))
SOURCES.append(("data/SRR_Acc_List.txt", KIT / "staged-data/data/SRR_Acc_List.txt", "the 8 workshop runs, samples.txt order"))
SOURCES.append(("data/tx2gene.tsv", KIT / "staged-data/data/tx2gene.tsv", "episode 04b command on gencode.vM38.transcripts.fa"))
for f in sorted((KIT / "staged-scripts").iterdir()):
    SOURCES.append(("scripts/" + f.name, f, "episodes, via build_kit.py"))


WORKSHOP_RUNS = ["SRR2121786", "SRR2121787", "SRR2121788", "SRR2121789",   # WT_Bcell_IR_rep1-4
                 "SRR2121778", "SRR2121779", "SRR2121780", "SRR2121781"]   # WT_Bcell_mock_rep1-4 (samples.txt order)


def make_staged_data():
    """Regenerate staged-data/ (not stored in git): the 8-run accession list and tx2gene.tsv,
    the latter with the Episode 04b command (FASTA headers: transcript ID, gene ID)."""
    d = KIT / "staged-data/data"
    d.mkdir(parents=True, exist_ok=True)
    (d / "SRR_Acc_List.txt").write_text("\n".join(WORKSHOP_RUNS) + "\n")
    fa = LT / "scratch/rnaseq-workshop/data/gencode.vM38.transcripts.fa"
    with open(fa) as fh, open(d / "tx2gene.tsv", "w") as out:
        for line in fh:
            if line.startswith(">"):
                f = line[1:].rstrip("\n").split("|")
                out.write("%s\t%s\n" % (f[0], f[1]))


def md5(p):
    h = hashlib.md5()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    make_staged_data()
    rows = ["# Expected content of the staged learner copy ($STAGED). Generated by make_staged_manifest.py;",
            "# do not edit. Anything else in $STAGED (indexes, results/, job logs) is an error.",
            "path\ttype\tbytes\tmd5\tneed\tsource"]
    rows += ["data\tdir\t-\t-\trequired\tsetup.md", "scripts\tdir\t-\t-\trequired\tsetup.md"]
    for rel, src, note in SOURCES:
        rows.append("%s\tfile\t%d\t%s\trequired\t%s" % (rel, src.stat().st_size, md5(src), note))
        print("%-55s %s" % (rel, rows[-1].split("\t")[3]))
    (KIT / "staged_manifest.tsv").write_text("\n".join(rows) + "\n")
    print("wrote %s (%d files)" % (KIT / "staged_manifest.tsv", len(SOURCES)))


if __name__ == "__main__":
    main()
